import React,{useState}from'react';import{Droplets,Factory,Shield,ArrowDown,CheckCircle2}from'lucide-react';import type{LucideIcon}from'lucide-react';import{useApp}from'../contexts/AppContext';
import { DamProcessAnimation } from '../components/DamProcessAnimation';
type Benefit=[string,string,LucideIcon];
const benefits:Benefit[]=[['Flood control','سیلاب پر قابو',Shield],['Irrigation','آبپاشی',Droplets],['Hydropower','پن بجلی',Factory]];
const t=(l:'en'|'ur'|'both',en:string,ur:string)=>l==='en'?<>{en}</>:l==='ur'?<span className="font-urdu" dir="rtl">{ur}</span>:<><span>{en}</span><span className="block font-urdu mt-1" dir="rtl">{ur}</span></>;
export function DamsPage(){const{language}=useApp();const[step,setStep]=useState(0);const steps: Array<[string,string,string,string]> = [['Reservoir','ذخیرہ','A dam stores water in a reservoir for later use.','ڈیم پانی کو ذخیرے میں محفوظ کرتا ہے تاکہ بعد میں استعمال ہو سکے۔'],['Controlled flow','قابو شدہ بہاؤ','Gates regulate how much water moves downstream.','گیٹس نیچے جانے والے پانی کی مقدار کو قابو کرتے ہیں۔'],['Turbines','ٹربائنیں','Moving water can spin turbines to generate electricity.','بہتا ہوا پانی ٹربائن کو گھما کر بجلی پیدا کر سکتا ہے۔'],['Distribution','تقسیم','Stored water can support irrigation and communities.','ذخیرہ شدہ پانی آبپاشی اور آبادیوں کی ضروریات پوری کر سکتا ہے۔']];return <div className="space-y-8 pb-10">{<section className="rounded-3xl p-7 md:p-11 text-white overflow-hidden relative" style={{background:'linear-gradient(135deg,#082f49,#0e7490,#164e63)'}}><Droplets className="absolute -right-6 -bottom-8 w-44 h-44 opacity-10"/><p className="text-cyan-200 text-sm font-bold">{t(language,'EARTH & WATER','زمین اور پانی')}</p><h1 className="text-4xl md:text-5xl font-black mt-3">{t(language,'Dams & Water Resources','ڈیم اور آبی وسائل')}</h1><p className="max-w-3xl mt-4 text-white/75 leading-7">{t(language,'A dam is a structure built to control, store, or redirect water. It connects water management, irrigation, flood control and sometimes electricity generation.','ڈیم ایک ایسا ڈھانچہ ہے جو پانی کو ذخیرہ، قابو یا منتقل کرنے کے لیے بنایا جاتا ہے۔ یہ آبی انتظام، آبپاشی، سیلاب سے تحفظ اور بعض اوقات بجلی پیدا کرنے سے جڑا ہوتا ہے۔')}</p></section>}<DamProcessAnimation />

      <Link to="/dams/guide" className="inline-flex items-center gap-2 rounded-xl px-5 py-3 font-black text-white bg-cyan-600 hover:bg-cyan-500 transition-colors"><BookOpen size={18}/> Full Dam Engineering Guide →</Link><section className="rounded-3xl border p-6 md:p-8" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-2xl font-black">{t(language,'How a dam works','ڈیم کیسے کام کرتا ہے')}</h2><div className="mt-8 grid md:grid-cols-4 gap-3">{steps.map((s,i)=><button key={s[0]} onClick={()=>setStep(i)} className="text-left rounded-2xl p-5 border transition-all hover:-translate-y-1" style={{backgroundColor:i===step?'color-mix(in srgb, var(--accent) 12%, var(--surface))':'var(--surface)',borderColor:i===step?'var(--accent)':'var(--border)'}}><div className="w-9 h-9 rounded-xl grid place-items-center font-black" style={{backgroundColor:'var(--accent)',color:'white'}}>{i+1}</div><h3 className="font-bold mt-4">{t(language,s[0],s[1])}</h3><p className="text-sm mt-2" style={{color:'var(--text-secondary)'}}>{t(language,s[2],s[3])}</p></button>)}</div><div className="mt-8 rounded-3xl p-6 overflow-hidden" style={{background:'linear-gradient(180deg,#dbeafe,#eff6ff)'}}><div className="relative h-56"><div className="absolute left-0 right-0 top-8 h-32 rounded-t-[40%] bg-sky-400/70"/><div className="absolute left-[36%] top-12 w-32 h-44 bg-slate-500 rounded-t-xl skew-x-[-8deg]"/><div className="absolute left-[45%] top-28 w-14 h-20 bg-slate-700 rounded-b-full animate-pulse"/><ArrowDown className="absolute left-[47%] top-28 text-white"/><div className="absolute right-4 bottom-2 text-slate-700 font-bold flex gap-2"><Factory/> {t(language,'Hydropower','پن بجلی')}</div></div></div></section><section className="rounded-3xl border p-6 md:p-8" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}>
<h2 className="text-2xl md:text-3xl font-black">{t(language,'What parts make a dam system work?','ڈیم سسٹم کے اہم حصے کون سے ہیں؟')}</h2>
<div className="mt-6 grid md:grid-cols-2 gap-4">
{[
['Reservoir','ذخیرہ','Stores water and creates a controllable hydraulic head.'],
['Dam body','ڈیم کا ڈھانچہ','Resists water pressure and transfers loads safely into the foundation.'],
['Intake & gates','انٹیک اور گیٹس','Controls when and how much water enters the outlet or power system.'],
['Penstock','پریشر پائپ','Carries water under pressure toward the turbine in a hydropower plant.'],
['Spillway','اسپل وے','Provides a controlled path for excess water so the reservoir does not overtop the dam.'],
['Turbine + generator','ٹربائن + جنریٹر','Converts the energy of moving water into mechanical rotation and then electricity.']
].map(([en,ur,d])=><article key={en} className="rounded-2xl border p-5" style={{borderColor:'var(--border)',background:'var(--surface-muted)'}}><h3 className="font-black text-lg">{t(language,en,ur)}</h3><p className="mt-2 text-sm leading-6" style={{color:'var(--text-secondary)'}}>{d}</p></article>)}
</div>
</section>
<section className="rounded-3xl border p-6 md:p-8" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}>
<h2 className="text-2xl md:text-3xl font-black">{t(language,'How water actually enters a dam reservoir','پانی ڈیم کے ذخیرے میں کیسے آتا ہے؟')}</h2>
<div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-5 gap-3">
{['Rainfall','Snowmelt','Tributaries','Groundwater','Upstream releases'].map((x,i)=><div key={x} className="rounded-2xl border p-4 text-center" style={{borderColor:'var(--border)',background:'var(--surface-muted)'}}><div className="mx-auto w-10 h-10 rounded-full grid place-items-center bg-cyan-500 text-white font-black">{i+1}</div><b className="block mt-3">{x}</b></div>)}
</div>
<p className="mt-5 leading-7" style={{color:'var(--text-secondary)'}}>{t(language,'A reservoir is normally filled by the river and tributaries draining its watershed, direct rainfall, snowmelt and sometimes groundwater or transfers from other water systems. The dam itself does not create water; it changes storage and flow.','ریزروائر عموماً اس کے catchment سے آنے والے دریا اور معاون دریاؤں، براہِ راست بارش، برف پگھلنے اور بعض صورتوں میں زیرِ زمین پانی یا دوسرے آبی نظاموں سے منتقل شدہ پانی سے بھرتا ہے۔ ڈیم پانی پیدا نہیں کرتا بلکہ پانی کے ذخیرے اور بہاؤ کو تبدیل کرتا ہے۔')}</p>
</section>
<section className="rounded-3xl border p-6 md:p-8" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}>
<h2 className="text-2xl md:text-3xl font-black">{t(language,'Different dam types','ڈیم کی مختلف اقسام')}</h2>
<div className="mt-6 grid md:grid-cols-2 xl:grid-cols-4 gap-4">
{[['Gravity','گریوٹی','Uses its own mass to resist water pressure.'],['Arch','آرچ','Curves the load into the surrounding canyon walls.'],['Embankment','ایم بینکمنٹ','Built from compacted earth or rockfill with engineered seepage control.'],['Buttress','بٹرس','Uses supports to transfer water loads to the foundation.']].map(([en,ur,d])=><article key={en} className="rounded-2xl border p-5" style={{borderColor:'var(--border)',background:'var(--surface-muted)'}}><h3 className="font-black">{t(language,en,ur)}</h3><p className="text-sm mt-2 leading-6" style={{color:'var(--text-secondary)'}}>{d}</p></article>)}
</div>
</section><section className="grid md:grid-cols-3 gap-4">{benefits.map(([a,b,I])=><div key={a as string} className="rounded-2xl border p-5" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}><I size={25} style={{color:'var(--accent)'}}/><h3 className="font-bold mt-3">{t(language,a as string,b as string)}</h3><div className="flex items-center gap-2 text-sm mt-2" style={{color:'var(--text-secondary)'}}><CheckCircle2 size={15}/> {t(language,'Key use of controlled water','قابو شدہ پانی کا اہم استعمال')}</div></div>)}</section></div>}
