import React,{useState} from 'react';
import {useApp} from '../contexts/AppContext';
import {Sun, Zap, BatteryCharging, Home, ArrowRight, CheckCircle2} from 'lucide-react';
export function SolarEnergyPage(){
 const {language}=useApp(); const [active,setActive]=useState(0);
 const text=(en:string,ur:string)=>language==='en'?<>{en}</>:language==='ur'?<span className="font-urdu" dir="rtl">{ur}</span>:<><span>{en}</span><span className="block font-urdu mt-1" dir="rtl">{ur}</span></>;
 const steps=[['Sunlight hits panels','سورج کی روشنی پینلز پر پڑتی ہے'],['Cells generate electricity','سیلز بجلی پیدا کرتے ہیں'],['Inverter converts current','انورٹر کرنٹ کو تبدیل کرتا ہے'],['Battery or grid stores/uses it','بیٹری یا گرڈ اسے محفوظ یا استعمال کرتا ہے']];
 return <div className="space-y-8 pb-10">
 <section className="rounded-3xl p-8 md:p-12 border" style={{background:'linear-gradient(135deg,#422006,#a16207,#0f172a)',borderColor:'var(--border)'}}><Sun size={44} className="text-amber-300"/><h1 className="text-4xl md:text-6xl font-black text-white mt-4">{text('Solar Energy','شمسی توانائی')}</h1><p className="mt-4 max-w-3xl text-white/75 leading-7">{text('Solar energy converts sunlight into useful heat or electricity. Explore the complete path from sunlight to a usable electrical load.','شمسی توانائی سورج کی روشنی کو مفید حرارت یا بجلی میں تبدیل کرتی ہے۔ روشنی سے بجلی کے استعمال تک مکمل عمل سمجھیں۔')}</p></section>
 <section className="rounded-2xl border p-6" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-2xl font-bold mb-6">{text('Animated energy flow','توانائی کا متحرک فلو')}</h2><div className="flex flex-wrap items-center justify-center gap-3">{steps.map((s,i)=><React.Fragment key={s[0]}><button onClick={()=>setActive(i)} className="rounded-2xl border p-4 min-w-[160px] text-center transition-all hover:-translate-y-1" style={{borderColor:i===active?'var(--accent)':'var(--border)',backgroundColor:i===active?'color-mix(in srgb,var(--accent) 12%,var(--surface))':'var(--surface-muted)'}}><div className="text-xs font-bold">{text(s[0],s[1])}</div></button>{i<3&&<ArrowRight style={{color:'var(--accent)'}}/>}</React.Fragment>)}</div><div className="mt-6 rounded-2xl p-6 text-center" style={{background:'linear-gradient(135deg,#111827,#1e3a5f)'}}><div className="flex justify-center gap-10 items-center"><Sun className="text-amber-300 animate-pulse" size={55}/><div className="h-1 w-20 bg-amber-300/60 overflow-hidden"><div className="h-full w-1/3 bg-white animate-[pulse_1s_infinite]"/></div>{active<2?<Zap className="text-yellow-200" size={50}/>:active===2?<BatteryCharging className="text-cyan-200" size={50}/>:<Home className="text-white" size={50}/>}</div><p className="text-white/80 mt-4 text-sm">{text(steps[active][0],steps[active][1])}</p></div></section>
 <section className="grid md:grid-cols-2 gap-4">{[['Benefits','فوائد',['Renewable source','Low operating emissions','Can work on rooftops']],['System parts','نظام کے حصے',['Solar panels','Inverter','Battery / grid connection']]].map(([h,hu,items])=><div className="rounded-2xl border p-6" style={{backgroundColor:'var(--surface)',borderColor:'var(--border)'}}><h2 className="font-bold text-xl">{text(h as string,hu as string)}</h2><div className="space-y-3 mt-4">{(items as string[]).map((x,i)=><div className="flex gap-2 text-sm" style={{color:'var(--text-secondary)'}}><CheckCircle2 size={18} style={{color:'var(--success)'}}/>{text(x,['قابل تجدید ذریعہ','کم آپریٹنگ اخراج','چھت پر نصب کیا جا سکتا ہے','سولر پینلز','انورٹر','بیٹری / گرڈ کنکشن'][i+(h==='System parts'?3:0)])}</div>)}</div></div>)}</section>
 </div>;
}