import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ExternalLink, Waves, Droplets, Mountain, Snowflake, CloudRain, Database, Route, Info } from 'lucide-react';
import { useApp } from '../contexts/AppContext';

type Detail = {
  slug:string; category:string; title:string; urdu:string; summary:string; location:string; scale:string;
  why:string; how:string[]; facts:string[]; related:string[]; source:string; sourceUrl:string;
};

const details:Detail[] = [
 {slug:'ocean-pacific',category:'Ocean',title:'Pacific Ocean',urdu:'بحرالکاہل',summary:'The largest and deepest of the five named ocean regions of the global ocean.',location:'Between Asia/Australia and the Americas; extending toward Antarctica and the Arctic.',scale:'About 162 million km² in the NOAA ocean-basin reference; average depth about 4,000 m.',why:'The Pacific stores a very large share of ocean water and strongly influences climate, marine ecosystems and plate-tectonic activity.',how:['Surface currents redistribute heat around the basin.','Winds transfer momentum to the ocean surface and help drive currents.','At depth, temperature and salinity differences contribute to large-scale circulation.','The Pacific margin contains the Ring of Fire, where plate boundaries produce frequent earthquakes and volcanism.'],facts:['Challenger Deep in the Mariana Trench is the deepest known point in the ocean.','The Pacific is bordered by many island groups and major continental margins.'],related:['ocean-atlantic','ocean-indian','ocean-southern','ocean-arctic'],source:'NOAA Ocean Service',sourceUrl:'https://oceanservice.noaa.gov/facts/biggestocean.html'},
 {slug:'ocean-atlantic',category:'Ocean',title:'Atlantic Ocean',urdu:'بحرِ اوقیانوس',summary:'The second-largest named ocean region and a major pathway for global ocean circulation.',location:'Between the Americas to the west and Europe/Africa to the east.',scale:'About 106.46 million km² according to NOAA.',why:'The Atlantic connects major climate, weather and marine systems and contains important current systems.',how:['Wind-driven surface currents move warm and cold water.','In the North Atlantic, cooling and increased salinity can make surface water denser and contribute to deep-water formation.','The basin exchanges water with the Arctic and Southern Ocean regions.'],facts:['The Atlantic covers roughly one-fifth of Earth’s surface.','NOAA describes the North Atlantic as part of the global ocean conveyor circulation.'],related:['ocean-pacific','ocean-indian','ocean-southern','ocean-arctic'],source:'NOAA Ocean Service',sourceUrl:'https://oceanservice.noaa.gov/facts/atlantic.html'},
 {slug:'ocean-indian',category:'Ocean',title:'Indian Ocean',urdu:'بحرِ ہند',summary:'The third-largest named ocean region, strongly influenced by seasonal monsoon winds.',location:'Between Africa, Asia, Australia and the Southern Ocean region.',scale:'Roughly 70–75 million km² depending on the boundary definition used.',why:'Its circulation, heat storage and monsoon interactions affect weather and climate across a large part of the Indian Ocean region.',how:['Seasonal winds reverse direction in parts of the basin.','Surface currents redistribute heat and nutrients.','Water exchanges with the Southern Ocean, Atlantic and Pacific through global circulation.'],facts:['It contains important tropical, subtropical and monsoon-driven marine environments.','Its northern boundary is largely enclosed by Asia compared with the Pacific and Atlantic.'],related:['ocean-pacific','ocean-atlantic','ocean-southern'],source:'NOAA ocean-basin references',sourceUrl:'https://oceanservice.noaa.gov/facts/biggestocean.html'},
 {slug:'ocean-southern',category:'Ocean',title:'Southern Ocean',urdu:'بحرِ جنوبی',summary:'The ocean region surrounding Antarctica and a major link in global ocean circulation.',location:'Encircles Antarctica in the Southern Hemisphere.',scale:'Area varies by boundary convention; NOAA recognizes it as one of the five major ocean regions.',why:'Strong winds, cold water and the Antarctic Circumpolar Current connect the Atlantic, Pacific and Indian sectors around Antarctica.',how:['Powerful westerly winds drive the Antarctic Circumpolar Current.','Cold dense waters participate in global overturning circulation.','Sea ice forms and melts seasonally, exchanging heat and freshwater with the ocean.'],facts:['It is a key connection between the other major ocean regions.','Its waters interact closely with the Antarctic ice sheet and sea ice.'],related:['ocean-pacific','ocean-atlantic','ocean-indian','ocean-arctic'],source:'NOAA Ocean Service',sourceUrl:'https://oceanservice.noaa.gov/facts/howmanyoceans.html'},
 {slug:'ocean-arctic',category:'Ocean',title:'Arctic Ocean',urdu:'بحرِ منجمد شمالی',summary:'The smallest of the five named ocean regions and the most northerly.',location:'Surrounded by North America, Greenland, Europe and Asia around the North Pole.',scale:'About 15.6 million km²; average depth about 1,205 m according to NOAA.',why:'It is tightly connected to polar climate, sea ice, freshwater exchange and high-latitude ecosystems.',how:['Seasonal sea ice grows and melts with changes in sunlight and temperature.','Freshwater enters from rivers and precipitation and also through ocean exchange.','Ice and snow strongly affect how much sunlight the surface absorbs.'],facts:['NOAA identifies it as the smallest ocean basin.','Sea ice supports a food web that includes algae, zooplankton, fish and larger animals.'],related:['ocean-pacific','ocean-atlantic','ocean-southern'],source:'NOAA Ocean Service',sourceUrl:'https://oceanservice.noaa.gov/facts/smallestocean.html'},
 {slug:'river-nile',category:'River',title:'Nile River System',urdu:'دریائے نیل',summary:'One of the world’s longest river systems, flowing northward through northeastern Africa.',location:'Major tributaries include the White Nile and Blue Nile; the system reaches the Mediterranean Sea.',scale:'USGS lists the Nile at about 4,132 miles (about 6,650 km) in its referenced comparison.',why:'The Nile supports ecosystems, agriculture, transport, cities and reservoirs across a predominantly arid region.',how:['Rainfall in upstream catchments feeds tributaries.','Tributaries merge into the main river and transport water and sediment downstream.','Floodplains and reservoirs store and redistribute water.','The river ultimately discharges to the Mediterranean.'],facts:['Its exact length depends on which headwater is treated as the source.','The river basin crosses multiple countries and climate zones.'],related:['river-amazon','river-yangtze','river-mississippi'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/rivers-world-worlds-longest-rivers'},
 {slug:'river-amazon',category:'River',title:'Amazon River System',urdu:'دریائے ایمیزون',summary:'A vast South American river system famous for exceptional discharge and basin size.',location:'Flows across the Amazon Basin and reaches the Atlantic Ocean.',scale:'USGS lists the Amazon at about 4,000 miles (about 6,400 km) in its referenced comparison; length varies by source definition.',why:'The basin stores and moves enormous quantities of freshwater and supports one of Earth’s richest ecosystems.',how:['Rainfall over the basin feeds thousands of tributaries.','Water moves through floodplains, wetlands and channels.','Tributaries combine into the main stem and discharge freshwater to the Atlantic.'],facts:['USGS describes the Amazon as the world’s largest river by discharge.','The basin spans several South American countries.'],related:['river-nile','river-yangtze','river-mississippi'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/publications/amazon-measuring-a-mighty-river'},
 {slug:'river-yangtze',category:'River',title:'Yangtze River',urdu:'دریائے یانگ زی',summary:'Asia’s longest river and a major Chinese river system.',location:'Flows across China from the Tibetan Plateau region to the East China Sea.',scale:'USGS lists about 3,915 miles (about 6,300 km) in its world-river comparison.',why:'The river supports cities, agriculture, ecosystems, transport and major water infrastructure.',how:['Mountain precipitation and snowmelt feed upper reaches.','Tributaries add water along the basin.','Reservoirs and wetlands modify storage and flow.','The river carries water and sediment toward the coast.'],facts:['The basin includes a wide range of elevations and climates.','Its flow is strongly seasonal in many reaches.'],related:['river-nile','river-amazon','river-mississippi'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/rivers-world-worlds-longest-rivers'},
 {slug:'river-mississippi',category:'River',title:'Mississippi–Missouri River System',urdu:'دریائے مسسیپی–میسوری',summary:'A major North American river system draining a huge portion of the central United States.',location:'The Missouri joins the Mississippi system, which eventually reaches the Gulf of Mexico.',scale:'USGS lists the Missouri at about 2,540 miles and the Mississippi at about 2,340 miles in its referenced comparison; combined-system lengths depend on the chosen headwater.',why:'The basin is central to agriculture, navigation, ecosystems, flood management and freshwater transport in North America.',how:['Rain and snowmelt feed tributaries.','Tributaries join larger channels across the basin.','Levees, reservoirs and floodplains influence water movement.','The combined river system carries water and sediment to the Gulf.'],facts:['USGS notes that river length changes with the method used to trace headwaters.','The Mississippi Basin is the largest river basin in the United States.'],related:['river-nile','river-amazon','river-yangtze'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/rivers-world-worlds-longest-rivers'},
 {slug:'lake-caspian',category:'Lake',title:'Caspian Sea',urdu:'بحیرۂ کیسپین',summary:'A huge enclosed inland water body commonly called a sea but classified geographically as a lake.',location:'Between Europe and Asia, bordered by Russia, Kazakhstan, Turkmenistan, Iran and Azerbaijan.',scale:'Its area and level vary over time; it is the world’s largest enclosed inland water body by area.',why:'It is an important enclosed basin with distinctive salinity, fisheries, wetlands and complex water-level changes.',how:['River inflow, precipitation and groundwater add water.','Evaporation removes water because the basin has no natural outlet to the global ocean.','Water level responds to the balance among inflow, precipitation, evaporation and human use.'],facts:['Despite the name “Sea,” it is commonly treated as the world’s largest lake by area.','Its water is saline to varying degrees.'],related:['lake-superior','lake-victoria','lake-baikal','lake-tanganyika'],source:'USGS lake data reference',sourceUrl:'https://pubs.usgs.gov/wsp/1972/report.pdf'},
 {slug:'lake-superior',category:'Lake',title:'Lake Superior',urdu:'جھیل سپیریئر',summary:'The largest freshwater lake by surface area and one of North America’s Great Lakes.',location:'Between the United States and Canada.',scale:'About 82,000 km² of surface area is commonly reported in Great Lakes references.',why:'It stores a huge volume of freshwater and supports ecosystems, fisheries, transport and regional climate processes.',how:['Precipitation and tributaries add water.','Evaporation removes water from the lake surface.','Water exits through the St. Marys River into Lake Huron.'],facts:['It is the largest of the Great Lakes by surface area.','Its large thermal mass influences nearby weather.'],related:['lake-victoria','lake-baikal','lake-tanganyika'],source:'USGS Great Lakes references',sourceUrl:'https://www.usgs.gov/publications/metrics-ecosystem-status-large-aquatic-systems-a-global-comparison'},
 {slug:'lake-victoria',category:'Lake',title:'Lake Victoria',urdu:'جھیل وکٹوریہ',summary:'Africa’s largest lake by surface area and an important freshwater ecosystem.',location:'Between Tanzania, Uganda and Kenya.',scale:'About 59,000 km² of surface area is commonly reported.',why:'The lake supports fisheries, biodiversity, transport and communities around its shoreline.',how:['Rainfall is a major water input.','Numerous streams and small rivers feed the lake.','Water leaves mainly through the Nile system at its northern outlet.'],facts:['USGS research groups Lake Victoria among large ecosystems affected by watershed and human pressures.','Its shallow-to-moderate depth makes it sensitive to environmental changes.'],related:['lake-superior','lake-baikal','lake-tanganyika'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/publications/metrics-ecosystem-status-large-aquatic-systems-a-global-comparison'},
 {slug:'lake-baikal',category:'Lake',title:'Lake Baikal',urdu:'جھیل بائیکال',summary:'An ancient rift lake in Siberia and the world’s deepest lake.',location:'Southern Siberia, Russia.',scale:'More than 1,600 m deep and about 23,000 km³ of water according to USGS.',why:'Baikal is a major freshwater store and a unique geological and biological system.',how:['Rivers and precipitation supply the lake.','Water is stored in the deep rift basin.','The Angara River provides the main surface outflow.'],facts:['USGS describes Baikal as the deepest lake in the world.','Its sediments preserve a long record of environmental and climate change.','It contains roughly 20% of the world’s surface freshwater according to the cited USGS fact sheet.'],related:['lake-superior','lake-victoria','lake-tanganyika'],source:'U.S. Geological Survey',sourceUrl:'https://pubs.usgs.gov/fs/baikal/'},
 {slug:'lake-tanganyika',category:'Lake',title:'Lake Tanganyika',urdu:'جھیل ٹانگانیکا',summary:'A very deep East African rift lake with a long, narrow basin.',location:'Between Tanzania, Democratic Republic of the Congo, Burundi and Zambia.',scale:'Among the deepest lakes on Earth, with a maximum depth around 1,470 m.',why:'Its great depth, age and rift setting create distinctive habitats and an important freshwater ecosystem.',how:['Rainfall and tributaries feed the lake.','Water is stored in a deep tectonic basin.','The lake drains through the Lukuga River toward the Congo system.'],facts:['It is one of the world’s largest rift-valley lakes.','Its deep basin is linked to tectonic extension of the East African Rift.'],related:['lake-baikal','lake-victoria','lake-superior'],source:'USGS large-lake research',sourceUrl:'https://www.usgs.gov/publications/metrics-ecosystem-status-large-aquatic-systems-a-global-comparison'},
 {slug:'water-oceans',category:'Water store',title:'Water in the Oceans',urdu:'سمندروں میں پانی',summary:'Most of Earth’s water is stored in the global ocean and is saline.',location:'The connected global ocean surrounding and separating the continents.',scale:'USGS estimates about 1.338 billion km³ of water in oceans, around 96.5% of all Earth water.',why:'The ocean is Earth’s largest water reservoir and a central driver of the water cycle, climate and marine life.',how:['Solar energy drives evaporation from the ocean surface.','Atmospheric transport moves water vapor over land and sea.','Precipitation returns water to the surface.','Rivers and groundwater return freshwater to the ocean.'],facts:['NOAA emphasizes that there is one global ocean divided geographically into named regions.','Most ocean water is saline, so it is not directly usable as ordinary freshwater.'],related:['water-groundwater','water-glaciers','water-atmosphere'],source:'U.S. Geological Survey / NOAA',sourceUrl:'https://www.usgs.gov/water-science-school/science/how-much-water-there-earth'},
 {slug:'water-groundwater',category:'Water store',title:'Groundwater',urdu:'زیرِ زمین پانی',summary:'Water stored below Earth’s surface in soil pores, sediments and fractured rock.',location:'Aquifers and pore spaces beneath the land surface.',scale:'USGS estimates roughly 23.4 million km³ of groundwater globally, with the exact partition depending on the dataset.',why:'Groundwater supplies wells, springs, ecosystems and baseflow to many rivers.',how:['Rain and snowmelt infiltrate the ground.','Water percolates downward through permeable material.','It accumulates in aquifers and moves slowly under gravity and pressure.','Wells and springs can bring groundwater back to the surface.'],facts:['Not all groundwater is fresh.','Groundwater can take years to millennia to move through some aquifers.'],related:['water-oceans','water-glaciers','water-atmosphere'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/how-much-water-there-earth'},
 {slug:'water-glaciers',category:'Water store',title:'Ice Caps & Glaciers',urdu:'برفانی چادریں اور گلیشیئر',summary:'Frozen freshwater stored in glaciers and ice sheets, including Antarctica and Greenland.',location:'Polar regions and high mountain ranges.',scale:'USGS estimates about 24.064 million km³ in ice caps, glaciers and permanent snow in its global water table.',why:'Ice stores a large share of Earth’s freshwater and strongly affects sea level, albedo and regional water supply.',how:['Snow accumulates where long-term snowfall exceeds melt and loss.','Compacted snow becomes glacier ice.','Ice flows slowly under gravity.','Melting produces runoff that can feed rivers and oceans.'],facts:['Most of Earth’s freshwater is locked in ice and glaciers.','Glaciers can act as seasonal or long-term water stores.'],related:['water-oceans','water-groundwater','water-atmosphere'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/how-much-water-there-earth'},
 {slug:'water-atmosphere',category:'Water store',title:'Water in the Atmosphere',urdu:'فضا میں پانی',summary:'Water exists in the atmosphere mainly as invisible vapor, clouds and precipitation.',location:'Troposphere and other atmospheric layers where water is transported and transformed.',scale:'USGS estimates atmospheric water at only a tiny fraction of total Earth water, about 12,900 km³ in its global table.',why:'Atmospheric water links evaporation to precipitation and moves freshwater around the planet.',how:['Evaporation and plant transpiration add vapor.','Rising air cools and can reach saturation.','Condensation forms cloud droplets or ice crystals.','Precipitation returns water to land and ocean.'],facts:['Atmospheric water has a tiny mass compared with the ocean, but it is central to weather.','Water can remain in the atmosphere for days to weeks while being transported.'],related:['water-oceans','water-groundwater','water-glaciers'],source:'U.S. Geological Survey',sourceUrl:'https://www.usgs.gov/water-science-school/science/how-much-water-there-earth'}
];

function Icon({category}:{category:string}){if(category==='Ocean')return <Waves/>;if(category==='River')return <Route/>;if(category==='Lake')return <Mountain/>;if(category==='Water store'&&category.includes('Ice'))return <Snowflake/>;return <Droplets/>;}

export function WaterDetailPage(){
 const {slug}=useParams(); const {language}=useApp(); const item=details.find(x=>x.slug===slug);
 const both=language==='both'; const ur=language==='ur';
 if(!item) return <div className="rounded-3xl border p-8" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h1 className="text-3xl font-black">Water topic not found</h1><Link className="text-cyan-500 font-bold inline-flex mt-4" to="/water-atlas"><ArrowLeft size={17}/> Back to Water Atlas</Link></div>;
 return <div className="space-y-7 pb-14">
  <Link to="/water-atlas" className="inline-flex items-center gap-2 font-bold" style={{color:'var(--accent)'}}><ArrowLeft size={18}/>{ur?'واپس آبی اٹلس':both?'Back to Water Atlas / آبی اٹلس':'Back to Water Atlas'}</Link>
  <section className="rounded-[2rem] border p-7 md:p-11 text-white overflow-hidden relative" style={{background:'linear-gradient(135deg,#042f3f,#075985,#0f766e)',borderColor:'rgba(125,211,252,.25)'}}>
   <Icon category={item.category}/>
   <div className="mt-4 text-xs uppercase tracking-[.2em] font-black text-cyan-200">{item.category}</div>
   <h1 className="mt-2 text-4xl md:text-6xl font-black">{item.title}</h1>
   <div className="font-urdu text-2xl mt-2" dir="rtl">{item.urdu}</div>
   <p className="mt-5 max-w-4xl text-white/85 leading-8">{item.summary}</p>
   {both&&<p className="font-urdu mt-3 text-white/80 leading-8" dir="rtl">{item.summary}</p>}
  </section>
  <section className="grid md:grid-cols-2 gap-5">
   <div className="rounded-3xl border p-6" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-xl font-black" style={{color:'var(--text-primary)'}}><Info className="inline mr-2 text-cyan-500"/>Location</h2><p className="mt-3 leading-7" style={{color:'var(--text-secondary)'}}>{item.location}</p></div>
   <div className="rounded-3xl border p-6" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-xl font-black" style={{color:'var(--text-primary)'}}>Scale & measurements</h2><p className="mt-3 leading-7" style={{color:'var(--text-secondary)'}}>{item.scale}</p></div>
  </section>
  <section className="rounded-3xl border p-6 md:p-8" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-2xl md:text-3xl font-black" style={{color:'var(--text-primary)'}}>Why it matters</h2><p className="mt-4 text-base leading-8" style={{color:'var(--text-secondary)'}}>{item.why}</p></section>
  <section className="rounded-3xl border p-6 md:p-8" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-2xl md:text-3xl font-black" style={{color:'var(--text-primary)'}}>How it works / How water moves</h2><div className="mt-5 grid gap-3">{item.how.map((x,i)=><div key={i} className="flex gap-3 rounded-2xl border p-4" style={{borderColor:'var(--border)',background:'var(--surface-muted)'}}><span className="w-8 h-8 rounded-full bg-cyan-500 text-white grid place-items-center font-black shrink-0">{i+1}</span><p className="leading-7" style={{color:'var(--text-primary)'}}>{x}</p></div>)}</div></section>
  <section className="rounded-3xl border p-6 md:p-8" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-2xl md:text-3xl font-black" style={{color:'var(--text-primary)'}}>Key facts</h2><div className="mt-5 grid md:grid-cols-2 gap-3">{item.facts.map((x,i)=><div key={i} className="rounded-2xl border p-4" style={{borderColor:'var(--border)'}}><p className="leading-7" style={{color:'var(--text-secondary)'}}>{x}</p></div>)}</div></section>
  <section className="rounded-3xl border p-6" style={{background:'var(--surface)',borderColor:'var(--border)'}}><h2 className="text-xl font-black" style={{color:'var(--text-primary)'}}>Official source</h2><p className="mt-2" style={{color:'var(--text-secondary)'}}>{item.source}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-3 font-bold text-cyan-500">Open source <ExternalLink size={16}/></a></section>
  <section><h2 className="text-2xl font-black" style={{color:'var(--text-primary)'}}>Explore related topics</h2><div className="mt-4 flex flex-wrap gap-2">{item.related.map(s=>{const r=details.find(x=>x.slug===s);return r?<Link key={s} to={'/water-atlas/'+s} className="rounded-full border px-4 py-2 text-sm font-bold hover:opacity-80" style={{borderColor:'var(--border)',color:'var(--text-primary)',background:'var(--surface)'}}>{r.title}</Link>:null})}</div></section>
 </div>;
}
